app_home:
    resource: ../../src/Shared/Presentation/Controller/
    type: annotation

app_api_hits:
    resource: ../../src/Hits/Presentation/Api/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
